(function(){
  const searchIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>';
  const downloadIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M5 21h14"/></svg>';
  const moreIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>';
  const meta={
    physio:[null,['Pacientes','Consulte prontuários, adesão e evolução clínica.'],['Agenda','Organize suas sessões e acompanhe o fluxo do dia.'],['Evoluções','Registre resultados e acompanhe metas terapêuticas.']],
    reception:[null,['Pacientes','Cadastros, contatos e situação de atendimento.'],['Agenda da clínica','Gerencie horários, confirmações e encaixes.'],['Cadastros','Documentos, acessos e pendências cadastrais.']],
    admin:[null,['Financeiro','Recebimentos, cobranças e desempenho mensal.'],['Equipe','Acessos, produtividade e disponibilidade dos profissionais.'],['Tutoriais','Biblioteca de exercícios e orientações aos pacientes.'],['Relatórios','Indicadores clínicos, operacionais e financeiros.']],
    patient:[null,['Meus exercícios','Seu plano domiciliar com orientações da fisioterapeuta.'],['Minha agenda','Próximas sessões e histórico de atendimentos.'],['Pagamentos','Mensalidades, recibos e formas de pagamento.']]
  };
  const toolbar=(title,subtitle,actions='')=>`<div class="screen-top"><div><h2>${title}</h2><p>${subtitle}</p></div><div class="screen-actions">${actions}</div></div>`;
  const search=(placeholder='Buscar...')=>`<label class="search-box">${searchIcon}<input placeholder="${placeholder}" data-screen-action="search"></label>`;
  const metric=(label,value,note='',attention=false)=>`<article class="metric-box ${attention?'attention':''}"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`;
  const person=(initials,name,metaText)=>`<div class="table-person"><div class="avatar">${initials}</div><div><b>${name}</b><small>${metaText}</small></div></div>`;
  const days=`<div class="day-strip">${[['SEG','21'],['TER','22'],['QUA','23'],['QUI','24'],['SEX','25'],['SÁB','26'],['DOM','27']].map((d,i)=>`<button class="day-chip ${i===6?'active':''}" data-screen-action="day"><span>${d[0]}</span><b>${d[1]}</b></button>`).join('')}</div>`;
  const detailViews={
    physio:{
      1:()=>`${toolbar('Carteira de pacientes','48 pacientes em acompanhamento',`${search('Buscar paciente')}<select class="select-clean" data-screen-action="filter"><option>Todos</option><option>Em tratamento</option><option>Alta próxima</option><option>Baixa adesão</option></select><button class="primary" data-screen-action="add-patient">${icons.plus} Novo paciente</button>`)}<div class="metric-row">${metric('Em tratamento','42','+3 no mês')}${metric('Alta prevista','6','Próximos 30 dias')}${metric('Baixa adesão','7','Requer acompanhamento',true)}</div><article class="panel flush"><div class="table-wrap"><table class="data-table"><thead><tr><th>Paciente</th><th>Tratamento</th><th>Última sessão</th><th>Adesão</th><th>Status</th><th></th></tr></thead><tbody><tr><td>${person('MC','Marina Costa','32 anos · (93) 99124-8890')}</td><td>Lombalgia crônica</td><td>Ontem</td><td><b>92%</b></td><td><span class="pill">Evoluindo</span></td><td><button class="ghost small" data-action="record" data-name="Marina Costa">Prontuário</button></td></tr><tr><td>${person('RS','Rafael Souza','44 anos · (93) 98410-2241')}</td><td>Pós-operatório joelho</td><td>Hoje</td><td><b>88%</b></td><td><span class="pill pink">Ativo</span></td><td><button class="ghost small" data-action="record" data-name="Rafael Souza">Prontuário</button></td></tr><tr><td>${person('LB','Lucas Barros','28 anos · (93) 99207-5540')}</td><td>Tendinopatia do ombro</td><td>25 set.</td><td><b>64%</b></td><td><span class="pill wait">Atenção</span></td><td><button class="ghost small" data-action="record" data-name="Lucas Barros">Prontuário</button></td></tr><tr><td>${person('IN','Isabela Nunes','53 anos · (93) 98115-7621')}</td><td>Artrose de quadril</td><td>23 set.</td><td><b>96%</b></td><td><span class="pill">Evoluindo</span></td><td><button class="ghost small" data-action="record" data-name="Isabela Nunes">Prontuário</button></td></tr><tr><td>${person('AF','André Freitas','39 anos · (93) 98862-1004')}</td><td>Cervicalgia</td><td>20 set.</td><td><b>48%</b></td><td><span class="pill wait">Baixa adesão</span></td><td><button class="ghost small" data-action="record" data-name="André Freitas">Prontuário</button></td></tr></tbody></table></div></article>`,
      2:()=>`${toolbar('Agenda de atendimentos','7 sessões agendadas para hoje',`${buttonNew('Novo atendimento','new-appointment')}`)}${days}<div class="detail-split"><article class="panel"><div class="panel-head"><div><h2>Domingo, 27 de setembro</h2><p>09:00 às 17:20</p></div><span class="pill pink">7 sessões</span></div><div class="agenda-list">${agendaItem('09:00','Marina Costa','4ª sessão · Lombalgia','pink','Na clínica')}${agendaItem('09:40','Rafael Souza','7ª sessão · Joelho','teal','Confirmado')}${agendaItem('10:20','Lucas Barros','Avaliação inicial · Ombro','amber','Confirmado')}${agendaItem('11:00','Isabela Nunes','6ª sessão · Quadril','teal','Confirmado')}${agendaItem('14:00','André Freitas','3ª sessão · Cervical','pink','A confirmar')}${agendaItem('15:30','Bianca Alves','8ª sessão · Tornozelo','teal','Confirmado')}</div></article><aside class="stack"><article class="panel"><div class="panel-head"><div><h2>Resumo do dia</h2><p>Capacidade da agenda</p></div></div><div class="summary-list"><div class="summary-line"><span>Confirmados</span><b>5 pacientes</b></div><div class="summary-line"><span>Aguardando confirmação</span><b>1 paciente</b></div><div class="summary-line"><span>Encaixes disponíveis</span><b>2 horários</b></div><div class="summary-line"><span>Ocupação</span><b>78%</b></div></div></article><article class="panel"><div class="panel-head"><div><h2>Lembretes</h2><p>Antes do próximo atendimento</p></div></div><div class="note-box"><b>Marina registrou nova observação</b><p>Relatou desconforto leve após o exercício de ponte.</p></div><button class="secondary full" style="margin-top:11px" data-action="record" data-name="Marina Costa">Revisar prontuário</button></article></aside></div>`,
      3:()=>`${toolbar('Evoluções clínicas','Acompanhe registros, metas e pendências',`<select class="select-clean" data-screen-action="filter"><option>Todos os pacientes</option><option>Esta semana</option><option>Pendentes</option></select><button class="primary" data-action="new-evolution">${icons.plus} Registrar evolução</button>`)}<div class="metric-row">${metric('Registradas na semana','26','+8% no período')}${metric('Pendentes','4','Concluir hoje',true)}${metric('Metas alcançadas','18','69% dos registros')}</div><div class="content-grid equal"><article class="panel"><div class="panel-head"><div><h2>Registros recentes</h2><p>Últimas avaliações clínicas</p></div></div><div class="progress-card"><div class="progress-score">+12°</div><div><b>Rafael Souza · Joelho</b><p>Ganho de amplitude e apoio sem dor. Progredir carga.</p></div><button class="ghost small" data-action="record" data-name="Rafael Souza">Abrir</button></div><div class="progress-card"><div class="progress-score">4→2</div><div><b>Marina Costa · Lombar</b><p>Redução de dor e melhora funcional nas atividades diárias.</p></div><button class="ghost small" data-action="record" data-name="Marina Costa">Abrir</button></div><div class="progress-card"><div class="progress-score">82%</div><div><b>Isabela Nunes · Quadril</b><p>Meta de caminhada alcançada, sem compensações.</p></div><button class="ghost small" data-action="record" data-name="Isabela Nunes">Abrir</button></div></article><article class="panel"><div class="panel-head"><div><h2>Pendências de registro</h2><p>Sessões ainda sem evolução</p></div><span class="pill wait">4 pendentes</span></div><div class="timeline"><div class="time-item"><time>Hoje</time><span class="rail"><i></i></span><div><b>Bianca Alves</b><small>Sessão das 08:20 · Tornozelo</small></div></div><div class="time-item"><time>Ontem</time><span class="rail"><i></i></span><div><b>Carlos Meireles</b><small>Sessão das 16:10 · Coluna cervical</small></div></div><div class="time-item"><time>25 set.</time><span class="rail"><i></i></span><div><b>Joana Ribeiro</b><small>Sessão das 14:40 · Punho</small></div></div></div><button class="primary full" data-action="new-evolution">Concluir próximo registro</button></article></div>`
    },
    reception:{
      1:()=>`${toolbar('Pacientes cadastrados','Localize contatos e acompanhe o cadastro',`${search('Nome, CPF ou telefone')}<button class="primary" data-screen-action="add-patient">${icons.plus} Cadastrar paciente</button>`)}<div class="metric-row">${metric('Total de pacientes','326','18 novos no mês')}${metric('Cadastros completos','309','94,8% da base')}${metric('Pendências','17','Documentos ou acesso',true)}</div><article class="panel flush"><div class="table-wrap"><table class="data-table"><thead><tr><th>Paciente</th><th>Contato</th><th>Plano</th><th>Próxima sessão</th><th>Cadastro</th><th></th></tr></thead><tbody><tr><td>${person('MC','Marina Costa','CPF final 442')}</td><td>(93) 99124-8890</td><td>Mensal</td><td>29 set. · 09:00</td><td><span class="pill">Completo</span></td><td><button class="ghost small" data-screen-action="edit-patient">Editar</button></td></tr><tr><td>${person('RS','Rafael Souza','CPF final 118')}</td><td>(93) 98410-2241</td><td>10 sessões</td><td>Hoje · 09:40</td><td><span class="pill">Completo</span></td><td><button class="ghost small" data-screen-action="edit-patient">Editar</button></td></tr><tr><td>${person('LB','Lucas Barros','CPF final 907')}</td><td>(93) 99207-5540</td><td>Avaliação</td><td>Hoje · 10:20</td><td><span class="pill wait">Falta documento</span></td><td><button class="ghost small" data-screen-action="edit-patient">Completar</button></td></tr><tr><td>${person('IN','Isabela Nunes','CPF final 024')}</td><td>(93) 98115-7621</td><td>Mensal</td><td>Hoje · 11:00</td><td><span class="pill pink">Sem acesso</span></td><td><button class="ghost small" data-screen-action="send-access">Enviar acesso</button></td></tr></tbody></table></div></article>`,
      2:()=>`${toolbar('Agenda da clínica','Visão geral de profissionais e salas',`${search('Buscar paciente')}<button class="primary" data-screen-action="new-appointment">${icons.plus} Agendar</button>`)}${days}<article class="panel"><div class="panel-head"><div><h2>Fluxo por profissional</h2><p>Domingo, 27 de setembro</p></div><select class="select-clean" data-screen-action="filter"><option>Todos os profissionais</option><option>Ana Lima</option><option>João Prado</option></select></div><div class="kanban"><section class="kanban-col"><div class="kanban-head"><b>Ana Lima</b><span>4</span></div>${kanbanCard('09:00','Marina Costa','Na clínica')}${kanbanCard('09:40','Rafael Souza','Confirmado')}${kanbanCard('10:20','Lucas Barros','Confirmado')}${kanbanCard('11:00','Isabela Nunes','Confirmado')}</section><section class="kanban-col"><div class="kanban-head"><b>João Prado</b><span>3</span></div>${kanbanCard('09:20','Bianca Alves','Em atendimento')}${kanbanCard('10:00','Carlos Meireles','Aguardando')}${kanbanCard('11:20','Joana Ribeiro','Confirmado')}</section><section class="kanban-col"><div class="kanban-head"><b>Encaixes disponíveis</b><span>3</span></div>${kanbanCard('13:20','Sala 1','Ana Lima')}${kanbanCard('14:40','Sala 2','João Prado')}${kanbanCard('16:00','Sala 1','Ana Lima')}</section></div></article>`,
      3:()=>`${toolbar('Central de cadastros','Acompanhe acessos, documentos e autorizações',`<button class="primary" data-screen-action="add-patient">${icons.plus} Novo cadastro</button>`)}<div class="feature-grid"><article class="feature-card"><div class="feature-icon">${icons.users}</div><h3>Cadastro de pacientes</h3><p>Dados pessoais, contatos e informações de acesso ao aplicativo.</p><footer><span>326 pacientes</span><button class="text-btn" data-screen-action="add-patient">Cadastrar</button></footer></article><article class="feature-card"><div class="feature-icon">${icons.file}</div><h3>Documentos e termos</h3><p>Controle de consentimentos, autorizações e documentos obrigatórios.</p><footer><span>8 pendências</span><button class="text-btn" data-screen-action="documents">Revisar</button></footer></article><article class="feature-card"><div class="feature-icon">${icons.wallet}</div><h3>Planos e convênios</h3><p>Vínculo do paciente com pacotes, mensalidades ou atendimento avulso.</p><footer><span>6 modalidades</span><button class="text-btn" data-screen-action="plans">Gerenciar</button></footer></article></div><div class="content-grid equal" style="margin-top:18px"><article class="panel"><div class="panel-head"><div><h2>Pendências cadastrais</h2><p>Itens que precisam de atenção</p></div><span class="pill wait">8 itens</span></div><div class="summary-list"><div class="summary-line"><span>Lucas Barros</span><b>Documento de identificação</b></div><div class="summary-line"><span>Isabela Nunes</span><b>Primeiro acesso ao app</b></div><div class="summary-line"><span>André Freitas</span><b>Termo de consentimento</b></div><div class="summary-line"><span>Bianca Alves</span><b>Contato de emergência</b></div></div></article><article class="panel"><div class="panel-head"><div><h2>Acessos enviados</h2><p>Últimos convites ao aplicativo</p></div></div><div class="timeline"><div class="time-item done"><time>08:12</time><span class="rail"><i></i></span><div><b>Pedro Martins</b><small>Acesso ativado</small></div></div><div class="time-item"><time>Ontem</time><span class="rail"><i></i></span><div><b>Larissa Gomes</b><small>Convite ainda não aberto</small></div></div><div class="time-item"><time>25 set.</time><span class="rail"><i></i></span><div><b>Renato Melo</b><small>Acesso ativado</small></div></div></div></article></div>`
    },
    admin:{
      1:()=>`${toolbar('Gestão financeira','Visão consolidada de setembro de 2026',`<select class="select-clean"><option>Setembro de 2026</option><option>Agosto de 2026</option></select><button class="secondary" data-screen-action="export">${downloadIcon} Exportar</button><button class="primary" data-screen-action="charge">${icons.plus} Nova cobrança</button>`)}<div class="stats">${stat('Receita confirmada','R$ 41.680','+12,4%','wallet')}${stat('A receber','R$ 3.480','Até 05/10','calendar')}${stat('Em atraso','R$ 1.760','8 cobranças','file',true)}${stat('Ticket médio','R$ 286','+R$ 18 no mês','activity')}</div><div class="content-grid"><article class="panel flush"><div class="panel-head" style="padding:20px 20px 0"><div><h2>Movimentações recentes</h2><p>Recebimentos e cobranças</p></div><button class="text-btn" data-screen-action="filter">Ver extrato completo</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Paciente</th><th>Referência</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr></thead><tbody><tr><td>${person('MC','Marina Costa','PIX')}</td><td>Mensalidade setembro</td><td>05 set.</td><td><b>R$ 280,00</b></td><td><span class="pill">Pago</span></td></tr><tr><td>${person('RS','Rafael Souza','Cartão')}</td><td>Pacote 10 sessões</td><td>12 set.</td><td><b>R$ 950,00</b></td><td><span class="pill">Pago</span></td></tr><tr><td>${person('AF','André Freitas','Boleto')}</td><td>Mensalidade setembro</td><td>10 set.</td><td><b>R$ 280,00</b></td><td><span class="pill wait">Em atraso</span></td></tr><tr><td>${person('IN','Isabela Nunes','PIX')}</td><td>Mensalidade outubro</td><td>05 out.</td><td><b>R$ 280,00</b></td><td><span class="pill gray">Pendente</span></td></tr></tbody></table></div></article><aside class="stack"><article class="panel"><div class="panel-head"><div><h2>Receita por serviço</h2><p>Distribuição mensal</p></div></div><div class="summary-list"><div class="summary-line"><span>Planos mensais</span><b>R$ 23.840 · 57%</b></div><div class="summary-line"><span>Pacotes de sessões</span><b>R$ 12.510 · 30%</b></div><div class="summary-line"><span>Avaliações avulsas</span><b>R$ 3.850 · 9%</b></div><div class="summary-line"><span>Outros serviços</span><b>R$ 1.480 · 4%</b></div></div></article><article class="panel"><div class="panel-head"><div><h2>Cobranças automáticas</h2><p>Próximo envio em 01/10</p></div><span class="pill">Ativas</span></div><p style="color:var(--muted);font-size:.82rem">42 pacientes receberão lembrete de vencimento pelo aplicativo.</p><button class="secondary full" data-screen-action="charge-settings">Configurar lembretes</button></article></aside></div>`,
      2:()=>`${toolbar('Equipe e acessos','9 profissionais ativos na clínica',`${search('Buscar profissional')}<button class="primary" data-action="new-access">${icons.plus} Criar acesso</button>`)}<div class="metric-row">${metric('Fisioterapeutas','6','Todos ativos')}${metric('Recepção','2','Cobertura completa')}${metric('Administradores','1','Acesso principal')}</div><div class="team-grid"><article class="team-card">${teamTop('AL','Ana Lima','Fisioterapeuta · Ortopedia')}<div class="team-stats"><div class="team-stat"><span>ATENDIMENTOS</span><b>68 no mês</b></div><div class="team-stat"><span>OCUPAÇÃO</span><b>88%</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article><article class="team-card">${teamTop('JP','João Prado','Fisioterapeuta · Esportiva')}<div class="team-stats"><div class="team-stat"><span>ATENDIMENTOS</span><b>61 no mês</b></div><div class="team-stat"><span>OCUPAÇÃO</span><b>82%</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article><article class="team-card">${teamTop('CM','Clara Mendes','Recepção')}<div class="team-stats"><div class="team-stat"><span>TRIAGENS</span><b>124 no mês</b></div><div class="team-stat"><span>CADASTROS</span><b>18 novos</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article><article class="team-card">${teamTop('LS','Lívia Santos','Fisioterapeuta · Neurológica')}<div class="team-stats"><div class="team-stat"><span>ATENDIMENTOS</span><b>54 no mês</b></div><div class="team-stat"><span>OCUPAÇÃO</span><b>76%</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article><article class="team-card">${teamTop('GM','Gabriel Moraes','Fisioterapeuta · Respiratória')}<div class="team-stats"><div class="team-stat"><span>ATENDIMENTOS</span><b>49 no mês</b></div><div class="team-stat"><span>OCUPAÇÃO</span><b>71%</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article><article class="team-card">${teamTop('BR','Beatriz Reis','Recepção')}<div class="team-stats"><div class="team-stat"><span>TRIAGENS</span><b>112 no mês</b></div><div class="team-stat"><span>CADASTROS</span><b>14 novos</b></div></div><button class="ghost" data-screen-action="edit-team">Gerenciar acesso</button></article></div>`,
      3:()=>`${toolbar('Biblioteca de tutoriais','24 vídeos disponíveis para os pacientes',`${search('Buscar tutorial')}<select class="select-clean"><option>Todas as categorias</option><option>Coluna</option><option>Joelho</option><option>Ombro</option></select><button class="primary" data-screen-action="add-tutorial">${icons.plus} Novo vídeo</button>`)}<div class="metric-row">${metric('Visualizações no mês','1.284','+18% no período')}${metric('Conclusão média','82%','Acima da meta')}${metric('Mais acessado','Mobilidade lombar','214 visualizações')}</div><div class="library-grid">${tutorial('Mobilidade lombar','Coluna · Ana Lima','04:32','214 visualizações','pink')}${tutorial('Ponte pélvica','Fortalecimento · Ana Lima','03:18','186 visualizações','teal')}${tutorial('Alongamento posterior','Mobilidade · João Prado','05:10','159 visualizações','amber')}${tutorial('Fortalecimento de joelho','Joelho · João Prado','06:42','142 visualizações','teal')}${tutorial('Mobilidade de ombro','Ombro · Lívia Santos','04:08','121 visualizações','pink')}${tutorial('Respiração diafragmática','Respiratória · Gabriel','03:56','98 visualizações','amber')}</div>`,
      4:()=>`${toolbar('Central de relatórios','Gere análises para decisões clínicas e administrativas',`<select class="select-clean"><option>Setembro de 2026</option><option>Últimos 3 meses</option><option>Este ano</option></select><button class="secondary" data-screen-action="export-all">${downloadIcon} Exportar resumo</button>`)}<div class="stats">${stat('Taxa de ocupação','82%','+6%','calendar')}${stat('Adesão média','86%','+8%','heart')}${stat('Altas no mês','18','+5 pacientes','activity')}${stat('Satisfação','4,8/5','126 avaliações','users')}</div><div class="report-grid"><article class="report-card"><div class="feature-icon">${icons.wallet}</div><div><h3>Relatório financeiro</h3><p>Receitas, atrasos, formas de pagamento e ticket médio.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article><article class="report-card"><div class="feature-icon">${icons.activity}</div><div><h3>Evolução clínica</h3><p>Metas alcançadas, dor, amplitude e progresso funcional.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article><article class="report-card"><div class="feature-icon">${icons.users}</div><div><h3>Produtividade da equipe</h3><p>Atendimentos, ocupação, registros e satisfação.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article><article class="report-card"><div class="feature-icon">${icons.calendar}</div><div><h3>Agenda e comparecimento</h3><p>Ocupação, faltas, cancelamentos e horários de pico.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article><article class="report-card"><div class="feature-icon">${icons.video}</div><div><h3>Uso dos tutoriais</h3><p>Visualizações, conclusão e exercícios mais acessados.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article><article class="report-card"><div class="feature-icon">${icons.file}</div><div><h3>Base de pacientes</h3><p>Novos cadastros, ativos, altas e perfil de atendimento.</p></div><button class="ghost small" data-screen-action="report">Gerar</button></article></div>`
    },
    patient:{
      1:()=>`${toolbar('Plano de exercícios','Orientações para hoje · cerca de 18 minutos',`<span class="pill pink" id="exerciseCount">1 de 3 concluídos</span>`)}<div class="detail-split"><section class="plan-list"><article class="plan-card"><div class="plan-media">${icons.play}</div><div><h3>Mobilidade lombar</h3><p>2 séries · 8 repetições · descanso de 30s</p><div class="sets"><i class="done"></i><i class="done"></i></div></div><button class="check checked" data-action="exercise">✓</button></article><article class="plan-card"><div class="plan-media">${icons.activity}</div><div><h3>Ponte pélvica</h3><p>3 séries · 10 repetições · movimento lento</p><div class="sets"><i></i><i></i><i></i></div></div><button class="check" data-action="exercise">✓</button></article><article class="plan-card"><div class="plan-media">${icons.heart}</div><div><h3>Alongamento posterior</h3><p>3 repetições · mantenha por 30 segundos</p><div class="sets"><i></i><i></i><i></i></div></div><button class="check" data-action="exercise">✓</button></article><article class="panel"><div class="panel-head"><div><h2>Como você se sentiu?</h2><p>Seu registro ajuda a ajustar o tratamento.</p></div></div><div class="form-grid"><div class="field"><label>Dor após os exercícios</label><select><option>Sem dor</option><option>Leve</option><option>Moderada</option><option>Forte</option></select></div><div class="field"><label>Dificuldade</label><select><option>Fácil</option><option>Adequada</option><option>Difícil</option></select></div><div class="field full-span"><label>Observação</label><textarea placeholder="Conte à Ana como foi..."></textarea></div></div><button class="primary" style="margin-top:12px" data-screen-action="save-feedback">Enviar relato</button></article></section><aside class="stack"><article class="panel next-card"><small>DICA DA ANA</small><h3>Respeite seu ritmo</h3><p>Interrompa o exercício se sentir dor forte ou diferente da habitual.</p><button class="white-btn" data-action="send-note">Falar com Ana →</button></article><article class="panel"><div class="panel-head"><div><h2>Progresso semanal</h2><p>5 dias de prática</p></div></div><div class="streak"><div class="day done"><span>✓</span><small>SEG</small></div><div class="day done"><span>✓</span><small>TER</small></div><div class="day done"><span>✓</span><small>QUA</small></div><div class="day done"><span>✓</span><small>QUI</small></div><div class="day done"><span>✓</span><small>SEX</small></div><div class="day today"><span>HOJE</span><small>SÁB</small></div></div></article></aside></div>`,
      2:()=>`${toolbar('Minha agenda','Próximas sessões e histórico',`<button class="secondary" data-screen-action="calendar-export">Adicionar ao calendário</button>`)}<div class="detail-split"><article class="panel"><div class="panel-head"><div><h2>Próximos atendimentos</h2><p>Seu plano atual</p></div><span class="pill pink">2 agendados</span></div><div class="agenda-list">${patientAgenda('29 SET','Terça-feira · 09:00','Ana Lima','4ª sessão · Lombalgia')}${patientAgenda('06 OUT','Terça-feira · 09:00','Ana Lima','5ª sessão · Reavaliação')}</div></article><aside class="panel"><div class="panel-head"><div><h2>Orientações</h2><p>Para seu próximo atendimento</p></div></div><div class="note-box"><b>Chegue 10 minutos antes</b><p>A recepção fará uma triagem rápida sobre seus exercícios e sintomas atuais.</p></div><div class="summary-list" style="margin-top:15px"><div class="summary-line"><span>Local</span><b>Clínica Movia · Sala 2</b></div><div class="summary-line"><span>Duração</span><b>40 minutos</b></div><div class="summary-line"><span>Profissional</span><b>Ana Lima</b></div></div></aside></div><article class="panel" style="margin-top:18px"><div class="panel-head"><div><h2>Histórico de sessões</h2><p>Atendimentos concluídos</p></div><button class="text-btn" data-screen-action="history">Ver histórico completo</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Profissional</th><th>Atendimento</th><th>Evolução</th><th></th></tr></thead><tbody><tr><td>22 set. · 09:00</td><td>Ana Lima</td><td>3ª sessão</td><td><span class="pill">Dor reduziu</span></td><td><button class="ghost small" data-screen-action="session-summary">Resumo</button></td></tr><tr><td>15 set. · 09:00</td><td>Ana Lima</td><td>2ª sessão</td><td><span class="pill">Mobilidade melhorou</span></td><td><button class="ghost small" data-screen-action="session-summary">Resumo</button></td></tr><tr><td>08 set. · 09:00</td><td>Ana Lima</td><td>1ª sessão</td><td><span class="pill pink">Plano iniciado</span></td><td><button class="ghost small" data-screen-action="session-summary">Resumo</button></td></tr></tbody></table></div></article>`,
      3:()=>`${toolbar('Pagamentos e recibos','Acompanhe seu plano e histórico financeiro',`<button class="secondary" data-screen-action="payment-method">Gerenciar forma de pagamento</button>`)}<div class="metric-row">${metric('Plano atual','Mensal','4 sessões por mês')}${metric('Próximo vencimento','05 out.','R$ 280,00',true)}${metric('Situação','Em dia','Nenhuma pendência')}</div><div class="content-grid"><article class="panel"><div class="panel-head"><div><h2>Mensalidades</h2><p>Últimos lançamentos</p></div></div><div class="invoice-list"><div class="invoice"><div class="invoice-date"><small>OUT</small>05</div><div><b>Mensalidade de outubro</b><p>Vence em 8 dias</p></div><strong>R$ 280,00</strong><button class="primary small" data-action="pay">Pagar</button></div><div class="invoice"><div class="invoice-date"><small>SET</small>05</div><div><b>Mensalidade de setembro</b><p>Pago via PIX em 04/09</p></div><strong>R$ 280,00</strong><button class="ghost small" data-screen-action="receipt">Recibo</button><span class="pill">Pago</span></div><div class="invoice"><div class="invoice-date"><small>AGO</small>05</div><div><b>Mensalidade de agosto</b><p>Pago via cartão em 05/08</p></div><strong>R$ 280,00</strong><button class="ghost small" data-screen-action="receipt">Recibo</button><span class="pill">Pago</span></div></div></article><aside class="stack"><article class="panel"><div class="panel-head"><div><h2>Forma de pagamento</h2><p>Preferência cadastrada</p></div></div><div class="note-box"><b>PIX</b><p>Pagamento confirmado de forma imediata pelo aplicativo.</p></div><button class="ghost full" style="margin-top:11px" data-screen-action="payment-method">Alterar preferência</button></article><article class="panel"><div class="panel-head"><div><h2>Precisa de ajuda?</h2><p>Fale com a recepção</p></div></div><p style="font-size:.82rem;color:var(--muted)">Em caso de dúvida sobre valores ou vencimentos, envie uma mensagem.</p><button class="secondary full" data-screen-action="billing-help">Conversar com a recepção</button></article></aside></div>`
    }
  };
  function buttonNew(label,action){return `<button class="primary" data-screen-action="${action}">${icons.plus} ${label}</button>`}
  function agendaItem(time,name,desc,color,status){return `<div class="agenda-item"><time>${time}</time><i class="agenda-accent ${color==='pink'?'':color}"></i><div><b>${name}</b><small>${desc}</small></div><div class="row-actions"><span class="pill ${status==='Na clínica'?'':status==='A confirmar'?'wait':'gray'}">${status}</span><button class="ghost small" data-screen-action="session">Detalhes</button></div></div>`}
  function kanbanCard(time,name,status){return `<article class="kanban-card"><time>${time}</time><b>${name}</b><small>${status}</small></article>`}
  function teamTop(initials,name,role){return `<div class="team-card-top"><div class="avatar">${initials}</div><div><h3>${name}</h3><p>${role}</p></div></div>`}
  function tutorial(title,category,duration,views,color){return `<article class="library-card"><div class="library-thumb ${color==='pink'?'':color}"><button class="play" data-action="play-video">${icons.play}</button><span class="duration">${duration}</span></div><div class="library-copy"><h3>${title}</h3><p>${category}</p><div class="library-meta"><span>${views}</span><button class="text-btn" data-screen-action="edit-tutorial">Editar</button></div></div></article>`}
  function patientAgenda(date,day,professional,desc){return `<div class="agenda-item"><div class="invoice-date"><small>${date.split(' ')[1]}</small>${date.split(' ')[0]}</div><i class="agenda-accent"></i><div><b>${day}</b><small>${professional} · ${desc}</small></div><div class="row-actions"><span class="pill">Confirmado</span><button class="ghost small" data-screen-action="reschedule">Reagendar</button></div></div>`}
  renderNav=function(){
    const p=profiles[currentRole],side=document.getElementById('sideNav'),mobile=document.getElementById('mobileNav');
    side.innerHTML=p.nav.map((n,i)=>`<button class="${i===activeNav?'active':''}" data-nav="${i}">${icons[n[0]]}<span>${n[1]}</span>${n[2]?`<i class="badge">${n[2]}</i>`:''}</button>`).join('');
    mobile.innerHTML=p.nav.map((n,i)=>`<button class="${i===activeNav?'active':''}" data-nav="${i}">${icons[n[0]]}<span>${n[1]}</span></button>`).join('');
    mobile.style.gridTemplateColumns=`repeat(${p.nav.length},1fr)`;
  };
  render=function(){
    const p=profiles[currentRole],screen=meta[currentRole][activeNav];
    document.getElementById('pageTitle').textContent=screen?screen[0]:p.title;
    document.getElementById('pageSubtitle').textContent=screen?screen[1]:p.subtitle;
    document.getElementById('userAvatar').textContent=p.initials;document.getElementById('userName').textContent=p.name;document.getElementById('userRole').textContent=p.label;document.getElementById('sideNoteTitle').textContent=p.noteTitle;document.getElementById('sideNoteText').textContent=p.noteText;
    document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===currentRole));renderNav();
    const target=document.getElementById('view');target.innerHTML=activeNav===0?views[currentRole]():detailViews[currentRole][activeNav]();target.classList.remove('view');void target.offsetWidth;target.classList.add('view');
  };
  function formPatient(){simpleForm('Cadastrar paciente',`<div class="field"><label>Nome completo</label><input placeholder="Nome do paciente"></div><div class="field"><label>CPF</label><input placeholder="000.000.000-00"></div><div class="field"><label>Telefone</label><input placeholder="(00) 00000-0000"></div><div class="field"><label>Data de nascimento</label><input type="date"></div><div class="field full-span"><label>Observação inicial</label><textarea placeholder="Queixa principal ou informação importante..."></textarea></div>`,'Paciente cadastrado e acesso enviado')}
  function formAppointment(){simpleForm('Novo agendamento',`<div class="field"><label>Paciente</label><select><option>Marina Costa</option><option>Rafael Souza</option><option>Lucas Barros</option></select></div><div class="field"><label>Profissional</label><select><option>Ana Lima</option><option>João Prado</option></select></div><div class="field"><label>Data</label><input type="date"></div><div class="field"><label>Horário</label><input type="time"></div>`,'Atendimento agendado com sucesso')}
  document.addEventListener('click',e=>{const el=e.target.closest('[data-screen-action]');if(!el)return;const action=el.dataset.screenAction;
    if(action==='add-patient')formPatient();
    else if(action==='new-appointment')formAppointment();
    else if(action==='session')openModal('Detalhes do atendimento','<div class="note-box"><b>Rafael Souza · 09:40</b><p>7ª sessão do protocolo pós-operatório de joelho. Paciente confirmou presença.</p></div><div class="summary-list" style="margin-top:15px"><div class="summary-line"><span>Profissional</span><b>Ana Lima</b></div><div class="summary-line"><span>Sala</span><b>Sala 2</b></div><div class="summary-line"><span>Duração</span><b>40 minutos</b></div></div>','<button class="primary" data-close>Fechar</button>');
    else if(action==='edit-patient')formPatient();
    else if(action==='send-access'){toast('Convite de acesso reenviado');}
    else if(action==='export'||action==='export-all'){toast('Relatório exportado com sucesso');}
    else if(action==='charge')simpleForm('Nova cobrança','<div class="field"><label>Paciente</label><select><option>André Freitas</option><option>Isabela Nunes</option></select></div><div class="field"><label>Valor</label><input value="R$ 280,00"></div><div class="field"><label>Vencimento</label><input type="date"></div><div class="field"><label>Forma</label><select><option>PIX</option><option>Boleto</option><option>Cartão</option></select></div>','Cobrança criada e enviada');
    else if(action==='add-tutorial')simpleForm('Adicionar tutorial','<div class="field full-span"><label>Título</label><input placeholder="Nome do exercício"></div><div class="field"><label>Categoria</label><select><option>Coluna</option><option>Joelho</option><option>Ombro</option></select></div><div class="field"><label>Profissional</label><select><option>Ana Lima</option><option>João Prado</option></select></div><div class="field full-span"><label>Orientações</label><textarea placeholder="Cuidados e execução correta..."></textarea></div>','Tutorial salvo na biblioteca');
    else if(action==='report'){toast('Relatório gerado e pronto para visualizar');}
    else if(action==='save-feedback'){toast('Relato enviado para Ana');}
    else if(action==='reschedule')openModal('Reagendar sessão','<div class="note-box"><b>Terça, 29 de setembro · 09:00</b><p>Solicite um novo horário. A recepção confirmará pelo aplicativo.</p></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Nova data</label><input type="date"></div><div class="field"><label>Preferência</label><select><option>Manhã</option><option>Tarde</option></select></div></div>','<button class="ghost" data-close>Cancelar</button><button class="primary" data-action="generic-save" data-success="Solicitação enviada à recepção">Solicitar</button>');
    else if(action==='receipt'){toast('Recibo preparado para download');}
    else if(action==='payment-method')simpleForm('Forma de pagamento','<div class="field full-span"><label>Preferência</label><select><option>PIX</option><option>Cartão de crédito</option><option>Cartão de débito</option></select></div>','Forma de pagamento atualizada');
    else if(action==='session-summary')openModal('Resumo da sessão','<div class="note-box"><b>Evolução positiva</b><p>A dor reduziu e a mobilidade melhorou. Continue o plano domiciliar conforme orientado.</p></div>','<button class="primary" data-close>Fechar</button>');
    else if(action==='edit-team')toast('Configurações de acesso abertas');
    else if(action==='day'){document.querySelectorAll('.day-chip').forEach(b=>b.classList.remove('active'));el.classList.add('active');toast('Agenda atualizada para o dia selecionado');}
    else if(action==='search'||action==='filter')return;
    else toast('Ação concluída no protótipo');
  });
  render();
})();
